function K_HSS = HSS1D_compress_fsym(type,X,TREE,acc,knl_params,options)
%
% This file is part of HSSC_DirectSolver
% Copyright (C) 2008-09 P.G. Martinsson (C) 2011-2013 E. Corona, P.G. Martinsson, D. Zorin
% See <COPYRIGHT_NOTICE.txt> for more details.
%
%
%    FUNCTION CALL:
%        K_HSS = HSS1D_compress_fsym(type,X,TREE,acc,knl_params,options)
%
%    DESCRIPTION:
%        This function compresses the symmetric kernel function matrix K[X,X] into HSS form (K_HSS)
%        using the given parameters. The symmetry of K engenders equal row and column skeletons.
%        Thus, K_HSS = D + L*Z*R, where D is symmetric and L = R'.
%
%    INFILE VARIABLES:
%        radius_rel (double) specifies the radius of the proxy circles relative to the box size.
%            default = 1.75.
%        nproxy (int) specifies the number of samples to be used on the proxy circles. default = 50.
%
%    INPUT:
%        type is a string in {'green', 'brute'} that specifies whether to use the Green's function
%            speedup to localize skeleten set computation (representing interactions with far field
%            points via a proxy) or a brute force construction.
%        X, given type='green' is an (N x 2) array with sorted points in a few layers along a curve
%            (usually a box boundary or an interface between two boxes).
%        X, given type='brute' is an (N x N) matrix K to be compressed using IDs on HSS block-rows
%            and columns
%        TREE can be a {7 x nboxes} cell array  that gives the underlying binary tree structure of
%            K_HSS. It can also be an integer that specifies the maximum total number of points per
%            leaf box, in which case a uniform tree is locally generated by subdividing X until
%            leaves are of size < TREE.
%        acc (double) is the desired accuracy.
%        knl_params is a struct of kernel evaluation parameters for type='green'. This can be
%            generated in ../Common/HSS_tree_parameters.m
%        options is a string specifying any extra parameters. Currently, options 'offd' is the only
%            supported argument, which opts to compress only top off-diagonal blocks
%        dim (int) is the dimension of the kernel (scalar -> dim = 1).
%
%    OUTPUT:
%        K_HSS is the cell array containing the HSS tree and skeleton information
%            (see ../Common/box_constants for details)
%


global BOX

% Option to turn our vector from scalar to vector (e.g. Stokes / Maxwell)
dim = 1; 

% Option for X to be in ambient dimension 2 (plane) or 3 (parametric
% surface)
if strcmp(type,'green')
D = knl_params.dim; 
if D==3
    T = knl_params.T;     
else
    T = X; 
end
end


% The following parameter can be tuned. 
% Setting it to 1.5 has proved a good balance in many cases.
radius_rel = 1.75;
nproxy = 50;          

% Compute the tree strcture.
ntot   = size(X,1);

if length(TREE) == 1
    nbox_max = TREE; 
    K_HSS  = LOCAL_get_tree(ntot,nbox_max);
    nboxes = size(K_HSS,2);
else 
    nboxes = size(TREE,2); 
    K_HSS  = cell(50,nboxes);
    K_HSS(BOX.DATA,:) = TREE(BOX.DATA,:); 
    clear TREE;
end

if strcmp(type,'green')
    % To perform the "green trick" we need to construct the list 
    % of neighbors for each cell.   
    LIST_NEI = LOCAL_construct_potential_neighborlist(T,K_HSS,radius_rel);    
    K_eval = true; 
    
elseif strcmp(type,'brute')
    % Second input is K matrix to be compressed with brute force
    K = X; 
    clear X; 
    K_eval = false; 
    depth = K_HSS{BOX.LEVEL,nboxes}; 
    I_src = cell(depth+1,1);   
end

% Compress all K_HSS, going from smaller to larger.
for ibox = nboxes:(-1):2

  % Construct the index vectors for ibox.
  if ( (K_HSS{BOX.C1,ibox}<=0) && (K_HSS{BOX.C2,ibox}<=0) ) % ibox has no sons.
      ind            = dim*K_HSS{BOX.END1,ibox} - dim + (1:dim*K_HSS{BOX.END2,ibox});
    indskel = ind;
  elseif ( (K_HSS{BOX.C1,ibox} > 0) && (K_HSS{BOX.C2,ibox} > 0) ) % ibox has two sons
    ison1       = K_HSS{BOX.C1,ibox};
    ison2       = K_HSS{BOX.C2,ibox};
    indskel = [K_HSS{BOX.I_SKUP,ison1},K_HSS{BOX.I_SKUP,ison2}];
  else
    ison = max([K_HSS{BOX.C1,ibox} K_HSS{BOX.C2,ibox}]);
    indskel = K_HSS{BOX.I_SKUP,ison};
  end
  
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  % Build A_out (block column or equivalent) and A_in (block row or equivalent)
  % to compress using ID. 
  
  if strcmp(type,'green')
        % Determine a circle that circumscribes the cell:
        [xxc,R] = LOCAL_get_circum_circle(T(sort(indskel),:));  
        % nproxy ~ 4*(2*pi*r)/(2*pi/k) + 50 = 4*k*r + 50, so there are 4 points per wavelength
        % (for oscillatory problems).
        if strcmp(knl_params.flag_pot,'SL_H_2D') || strcmp(knl_params.flag_pot,'SL_H_3D')
            nproxy = min(max(50,round(4*knl_params.kh*radius_rel*R + 30)),ntot);  
        end 
        Cproxy  = LOCAL_construct_circle(xxc, radius_rel*R, nproxy);
        % Find all contour points inside the circle:
        indskel_maybeinside = [];
        
        for jbox = LIST_NEI{ibox}
            if ( (K_HSS{BOX.C1,jbox}<=0) && (K_HSS{BOX.C2,jbox}<=0) )
                indskel_maybeinside = [indskel_maybeinside,dim*(K_HSS{BOX.END1,jbox}) - dim + (1:dim*K_HSS{BOX.END2,jbox})];
            elseif ( (K_HSS{BOX.C1,jbox}>0) && (K_HSS{BOX.C2,jbox}>0) )
                jbox_son1 = K_HSS{BOX.C1,jbox};
                jbox_son2 = K_HSS{BOX.C2,jbox};
                indskel_maybeinside = [indskel_maybeinside,K_HSS{BOX.I_SKUP,jbox_son1},K_HSS{BOX.I_SKUP,jbox_son2}];
            else
                jbox_son = max(K_HSS{BOX.C1,jbox},K_HSS{BOX.C2,jbox});
                indskel_maybeinside = [indskel_maybeinside,K_HSS{BOX.I_SKUP,jbox_son}];
            end
        end
  
        relind = find( ((T(indskel_maybeinside,1)-xxc(1)).^2 + ...
                  (T(indskel_maybeinside,2)-xxc(2)).^2) < ((radius_rel*R)^2) );
        indskel_inside = indskel_maybeinside(relind);
        
        % Circular proxy to perform green trick
        X_proxy = [Cproxy(1,:)' Cproxy(4,:)']; 
        
        if D == 3
           X_proxy = shape_3D(X_proxy,knl_params,knl_params.type); 
        end
  
        % A_out = K[X_inside U X_proxy, X_out]
        A_out = [Kernel_Eval(X(indskel_inside,:),X(indskel,:),knl_params);...
              Kernel_Eval(X_proxy,X(indskel,:),knl_params)]; 
        % A_in = A_out.' = K[X_in,X_inside U X_proxy]  
          
  elseif strcmp(type,'brute')
      lev = K_HSS{BOX.LEVEL,ibox}; 
      if ( (K_HSS{BOX.C1,ibox}<=0) && (K_HSS{BOX.C2,ibox}<=0) )
        % Neutered index (I \ I_i), could be improved to U_{j \neq i} {I_j^{src}}
         ind_offd = [1:(K_HSS{BOX.END1,ibox}-1),(K_HSS{BOX.END1,ibox}+K_HSS{BOX.END2,ibox}):ntot];
      else
          % Neutered index U_{j \neq i} {I_j^{src}}   
         ind_offd = I_src{lev+1}; 
         ind_offd(ind_offd>=K_HSS{BOX.END1,ibox} & ...
                  ind_offd<K_HSS{BOX.END1,ibox}+K_HSS{BOX.END2,ibox}) = [];     
      end
      
        % HSS block-column
        A_out = K(ind_offd,indskel);
        % HSS block-row is transpose of block-column
      
  end

  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  % Skeleton info (compression with ID)
  
  % Compute the skeletons.
  [Tout,Jout] = ID(A_out, acc);
  k = size(Tout,1);
  
  % Record the outgoing skeletons:
  K_HSS{BOX.I_SKUP,ibox} = indskel(Jout(1:k));
  K_HSS{BOX.T_UP,ibox} = Tout;
  K_HSS{BOX.J_UP,ibox} = Jout;
  % Record nskel and kskel
  K_HSS{BOX.NSKEL,ibox} = length(indskel);
  K_HSS{BOX.KSKEL,ibox} = k;
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  
  if strcmp(type,'brute') & K_HSS{BOX.LEVEL,ibox}>0
     lev = K_HSS{BOX.LEVEL,ibox};  
     I_src{lev} = [I_src{lev} K_HSS{BOX.I_SKUP,ibox} ];     
  end
end

% Construct the matrices representing self-interactions on the leaves and
% sibling interactions on children boxes
for ibox = nboxes:(-1):1
  if ( (K_HSS{BOX.C1,ibox}<=0) && (K_HSS{BOX.C2,ibox}<=0) )
    if nargin < 6 
        ind = dim*K_HSS{BOX.END1,ibox} - dim + (1:dim*K_HSS{BOX.END2,ibox});
        if K_eval
            K_HSS{BOX.M_SELF,ibox} = Kernel_Eval(X(ind,:),X(ind,:),knl_params); 
        else
            K_HSS{BOX.M_SELF,ibox} = K(ind,ind); 
        end
    elseif strcmp(options,'offd')
        % Self-interactions are zeroed out
        n = K_HSS{BOX.NSKEL,ibox}; 
        K_HSS{BOX.M_SELF,ibox} = sparse(n,n); 
    else
        % Might fit other options here
        ind = dim*K_HSS{BOX.END1,ibox} - dim + (1:dim*K_HSS{BOX.END2,ibox});
        if K_eval
            K_HSS{BOX.M_SELF,ibox} = Kernel_Eval(X(ind,:),X(ind,:),knl_params); 
        else
            K_HSS{BOX.M_SELF,ibox} = K(ind,ind); 
        end
    end
    
  elseif ( (K_HSS{BOX.C1,ibox}>0) && (K_HSS{BOX.C2,ibox}>0) )
    ison1 = K_HSS{BOX.C1,ibox};
    ison2 = K_HSS{BOX.C2,ibox};
    
    if nargin < 6 
        % Sibling interactions
        if K_eval
            K_HSS{BOX.M_SIB,ison1} = Kernel_Eval(X(K_HSS{BOX.I_SKUP,ison1},:),X(K_HSS{BOX.I_SKUP,ison2},:),knl_params); 
        else
            K_HSS{BOX.M_SIB,ison1} = K(K_HSS{BOX.I_SKUP,ison1}, K_HSS{BOX.I_SKUP,ison2}); 
        end
    elseif strcmp(options,'offd') & ibox>1 
        K_HSS{BOX.M_SIB,ison1} = sparse(K_HSS{BOX.KSKEL,ison1},K_HSS{BOX.KSKEL,ison2}); 
    else
        % Sibling interactions at top (and/or other options)
        if K_eval
            K_HSS{BOX.M_SIB,ison1} = Kernel_Eval(X(K_HSS{BOX.I_SKUP,ison1},:),X(K_HSS{BOX.I_SKUP,ison2},:),knl_params); 
        else
            K_HSS{BOX.M_SIB,ison1} = K(K_HSS{BOX.I_SKUP,ison1}, K_HSS{BOX.I_SKUP,ison2}); 
        end
    end
    
    K_HSS{BOX.M_SIB,ison2} = K_HSS{BOX.M_SIB,ison1}.'; 
    
  end
end

return

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function K_HSS = LOCAL_get_tree(ntot,nbox_max)
global BOX 

TREE = cell(7,2^ceil(log2(ntot/nbox_max)));    

% Construct the top node.
TREE{BOX.LEVEL,1} = 0;
TREE{BOX.PARENT,1} = NaN;
TREE{BOX.C1,1} = -1;
TREE{BOX.C2,1} = -1;
TREE{BOX.END1,1} = 1;
TREE{BOX.END2,1} = ntot;
ibox_last = 0;
ncreated  = 1;
ilevel    = 0;

% Create smaller K_HSS via hierarchical subdivision.
% We sweep one level at a time.
while (ncreated > 0)
  ibox_first = ibox_last + 1;
  ibox_last  = ibox_last + ncreated;
  ncreated   = 0;
  for ibox = ibox_first:ibox_last
    nbox = TREE{BOX.END2,ibox};
    if (nbox > nbox_max)
      nhalf             = ceil(nbox/2);
      ibox_son1         = ibox_last + ncreated + 1;
      ibox_son2         = ibox_last + ncreated + 2;
      TREE{BOX.C1,ibox}      = ibox_son1;
      TREE{BOX.C2,ibox}      = ibox_son2;
      TREE{BOX.LEVEL,ibox_son1} = ilevel+1;
      TREE{BOX.LEVEL,ibox_son2} = ilevel+1;
      TREE{BOX.PARENT,ibox_son1} = ibox;
      TREE{BOX.PARENT,ibox_son2} = ibox;
      TREE{BOX.C1,ibox_son1} = -1;
      TREE{BOX.C1,ibox_son2} = -1;
      TREE{BOX.C2,ibox_son1} = -1;
      TREE{BOX.C2,ibox_son2} = -1;
      TREE{BOX.END1,ibox_son1} = TREE{BOX.END1,ibox};
      TREE{BOX.END1,ibox_son2} = TREE{BOX.END1,ibox} + nhalf;
      TREE{BOX.END2,ibox_son1} = nhalf;
      TREE{BOX.END2,ibox_son2} = TREE{BOX.END2,ibox} - nhalf;
      ncreated          = ncreated + 2;
    end
  end
  ilevel = ilevel + 1;
end

nboxes = ibox_last;
K_HSS  = cell(50,nboxes);
K_HSS(1:7,:) = TREE(1:7,1:nboxes);   

return

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [xxc, R] = LOCAL_get_circum_circle(X)

nloc       = size(X,1);

% First we TRY to create the circle based on the endpoints.
xxc        = 0.5*(X(1,:) + X(end,:));
distsquare = (X(:,1)-xxc(1)).^2 + (X(:,2)-xxc(2)).^2;
R          = sqrt(max(distsquare));

% The result is an absurdly large circle, then we instead
% base it on the center of mass of the points.
if ( (1.2*R*R) > ( (X(1,1) - X(end,1))^2 + (X(1,2) - X(end,2))^2) )
  xxc        = (1/nloc)*[sum(X(:,1)); sum(X(:,2))];
  distsquare = (X(:,1)-xxc(1)).^2 + (X(:,2)-xxc(2)).^2;
  R          = sqrt(max(distsquare));
end

return

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function C = LOCAL_construct_circle(xxc, R, n)

tt = linspace(0, 2*pi*(1-1/n), n);
C  = [xxc(1) + R*cos(tt);...
             - R*sin(tt);...
             - R*cos(tt);...
      xxc(2) + R*sin(tt);...
             + R*cos(tt);...
             - R*sin(tt)];

return

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function LIST_NEI = LOCAL_construct_potential_neighborlist(X,K_HSS,radius_rel)
global BOX 

nboxes = size(K_HSS,2);

% Note that in the construction, we temporarily include
% a box in its own list of neighbors.
LIST_NEI    = cell(1,nboxes);
LIST_NEI{1} = [1];
for ibox = 2:nboxes
  [xxc, R] = LOCAL_get_circum_circle(X(K_HSS{BOX.END1,ibox}-1+(1:K_HSS{BOX.END2,ibox}),:));
  % Collect of list of all the father's neighbors' sons:
  potneis = [];
  for jbox = LIST_NEI{K_HSS{3,ibox}};
    if (K_HSS{BOX.C1,jbox} > 0)
      potneis = [potneis,K_HSS{BOX.C1,jbox}];
    end
    if (K_HSS{BOX.C2,jbox} > 0)
      potneis = [potneis,K_HSS{BOX.C2,jbox}];
    end
  end
  % Loop over all potential neighbors to check which ones are actually "close".
  for jbox = potneis
    ind    = K_HSS{BOX.END1,jbox} - 1 + (1:K_HSS{BOX.END2,jbox});
    distsq = (X(ind,1)-xxc(1)).^2 + (X(ind,2)-xxc(2)).^2;
    if (min(distsq) < radius_rel*radius_rel*R*R)
      LIST_NEI{ibox} = [LIST_NEI{ibox},jbox];
    end
  end
end
% Finally we remove the box itself from the list of neighbors.
for ibox = 2:nboxes
  j = find(LIST_NEI{ibox} == ibox);
  LIST_NEI{ibox} = sort(LIST_NEI{ibox}([1:(j-1),(j+1):end]));
end

return