function show_tree(info_tree)
%
% This file is part of HSSC_DirectSolver
% Copyright (C) 2011-2013 Eduardo Corona, Per Gunnar Martinsson, Denis Zorin
% See <COPYRIGHT_NOTICE.txt> for more details.
%
%
%     FUNCTION CALL:
%         show_tree(info_tree)
%
%     DESCRIPTION:
%         This function plots the leaves of an adaptive binary 'quadtree' generated by
%         HSS2D_bintree.m
%
%     INPUT:
%         info_tree   <struct>    (output of HSS2D_bintree_*) HSS binary tree. The interpolation
%                                     operators and skeleton sets are not needed (params.
%                                     DOskeletons=false as input to HSS2D_bintree_*) In
%                                     particular, the following tree info is needed
%             .levbox (int total_box x 1 array)   box level
%             .leaves (int numleaf x 2 array) leaves box numbers and level
%             .BOX (per box information):
%                 cent  (float total_box x 2 array) box center
%                 parent (int total_box x 1 array) box parents (0 for root node)
%                 child (int total_par x 2 array) box's children (non leaf boxes)
%
%




for i=1:length(info_tree.leaves)
    
    lev = info_tree.leaves(i,2); 
    cL = info_tree.BOX(info_tree.leaves(i,1)).cent; 
    
    if mod(lev,2) == 0
        box_sides = [lev/2 lev/2];
    else
        box_sides = [(lev+1)/2 (lev-1)/2];
    end
    
show_box(cL,box_sides,'r')
hold on
end

axis equal; axis tight; 